version: '2'
services:
  es:
    build: ./es/
    ports:
      - '9200:9200'
      - '9300:9300'
  kibana:
    build: ./kibana/
    ports:
      - '5601:5601'
    depends_on:
      - es
    links:
      - es
